backend:
  # Choose the backend you prefer (GitHub, GitLab, BitBucket)
  # Reference: https://www.netlifycms.org/docs/authentication-backends/
  name: github
  branch: master
  repo: Hardaker587/fractional_design
  accept_roles: 
    - admin
    - editor
  logo_url: https://fractionaldesign.co.za/assets/static/Logo_black.png
  
publish_mode: editorial_workflow
site_url: https://www.fractionaldesign.co.za

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "blogs"
    label: "Blogs"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "date" }
      - { label: "slug", name: "slug", widget: "string" }
      - { label: "body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", default: "../assets/images/Services.png" }

  - name: "pages"
    label: "Pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "slug", name: "slug", widget: "string" }
      - { label: "body", name: "body", widget: "markdown" }
      - { label: "Custom Styles", name: "customStyles", widget: "markdown", hint: "Include all markdown tags", required: false }
      - { label: "Custom Scripts", name: "customScripts", widget: "markdown", hint: "Include all markdown tags", required: false }
      - {label: "Featured Image", name: "thumbnail", widget: "image", default: "../assets/images/Services.png", required: false }
    folder: "sitePages"  
    
  - name: "portfolio"
    label: "Portfolio"
    folder: "portfolioArchive"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "date" }
      - { label: "slug", name: "slug", widget: "string" }
      - { label: "body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", default: "../assets/images/Services.png", required: false}